version: '3.3'
services: 
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    # depends_on:
    #   - certbot
    # volumes:
      # - ./user-data/nginx.conf:/etc/nginx/nginx.conf # Uncomment to use custom nginx.conf
      # - ./user-data/conf.d:/etc/nginx/conf.d
      # - ./user-data/letsencrypt:/etc/letsencrypt:ro         # Certificates from certbot
      # - ./certbot-www:/var/www/certbot:ro  # ACME challange files when certbot renews
      # - ./nginx-certbot.conf:/etc/nginx/nginx-certbot.conf  # .well-known path for certbot
  mongo:
    image: mongo:4.2.5
  app:
    build: .
    # image: public.ecr.aws/d4h2y0a4/grocery-app:latest
    restart: always
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - "8080:8080"
  # certbot:
  #   build: certbot-img/.  # Build custom certbot image, auto-renew
  #   container_name: certbot
  #   restart: unless-stopped
  #   volumes:
  #     - ./user-data/letsencrypt:/etc/letsencrypt # Certificates
  #     - ./certbot-www:/var/www/certbot           # For ACME challange