version: '3.3'
services: 
  nginx:
    build: ./nginx
    ports:
      - "242:80"
      - "443:443"
    volumes:
      - /srv/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /srv/nginx/conf.d:/etc/nginx/conf.d
      - /srv/nginx/cert:/etc/letsencrypt:ro
  mongo:
    image: mongo:4.2.5
  app:
    build: .
    # image: public.ecr.aws/d4h2y0a4/grocery-app:latest
    restart: always
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - "8080:8080"