version: '3.3'
services: 
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
  mongo:
    image: mongo:4.2.5
  app:
    build: .
    # image: public.ecr.aws/d4h2y0a4/grocery-app:latest
    restart: always
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - "8888:8080"